var errorCodesMap = {
	GENERAL: 0,
	AUTHENTICATION_PROBLEM: 1,
    INSUFFICIENT_PRIVILEGES: 3,
    SESSION_EXPIRED: 10,
    OBJECT_ALREADY_EXISTS: 100,
    YEAR_ALREADY_RUNNING: 1000,
    GRADE_NOT_NUMERICAL: 2000
};